apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      name: nginx
      labels:
        app: my-webserver
    spec:
      containers:
        - name: nginx
          image: rbandrews/randrews-test:ra-webserver

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      name: maria
      labels:
        app: my-db
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: persist-claim
      containers:
        - name: mariadb
          image: mariadb
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: db-storage
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: hunter2
